config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :game, only: [ :show, :create ] do
    post :ready
    post :not_ready

    resources :players, only: [ ] do
      post :kick      # TODO this would be a DELETE using REST
    end

    resources :board, only: [ :show ] do
      post :submit    # TODO this would be /guesses/create
    end
  end

  get "/auth/google_login/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", as: :logout

  get "sessions/new", as: :login
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :guesses, dependent: :destroy
  has_many :possible_words, dependent: :destroy

  belongs_to :game

  validates :round_number, :serialized_cells, :game, presence: true
  # TODO validation of uniqueness round_number on game
  # -> then round_number can be count(boards) rather than max(round_number) + 1
  # TODO checks that round_number increments

  # TODO make a 5x5 board OR make these constants on Board (WIDTH, HEIGHT)
  def width
    4
  end

  def height
    4
  end

  # TODO check that this is used in the JS
  def round_length
    3.minutes
  end

  # TODO use a time diff instead, time1.diff(time2).in_seconds > 3*60
  # (considering daylight savings)
  def expires_at
    created_at + round_length
  end

  def cells
    # TODO does board.update! cells: [[..]] work? add spec for custom serializer
    @cells ||= serialized_cells.split("|").map { |row| row.split(",") }
  end

  def cells=(rows)
    update(serialized_cells: rows.map { |row| row.join(",") }.join("|"))
  end

  def cell_at(x,y)
    cells[y][x]
  end
end

app/models/dictionary.rb
# TODO rename to Word or DictionaryWord
# TODO add prime number boggle
class Dictionary < ActiveRecord::Base
  validates :word, presence: true, uniqueness: true
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players, dependent: :destroy
  has_many :boards, dependent: :destroy

  scope :not_started, -> { where(started: false) }

  def target_score
    100
  end

  def rounds
    boards.maximum(:round_number) || 0
  end

  def ready_to_start?
    players.all?(&:ready?) && players.length >= 2
  end
end

app/models/guess.rb
class Guess < ActiveRecord::Base
  belongs_to :player
  belongs_to :board

  validates :player, :board, :word, presence: true
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :game

  has_many :guesses, dependent: :destroy

  scope :ready, -> { where(ready: true) }

  validates :user, :score, :game, presence: true
end

app/models/possible_word.rb
class PossibleWord < ActiveRecord::Base
  belongs_to :board
  belongs_to :dictionary
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :players, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
    if !current_user
      flash[:alert] = "You need to login"
      redirect_to :login
    end
  end

end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  before_filter :authenticate

  def show
    @game = find_game
    @board = find_board
    @guesses = find_guesses
    @player = find_player
  end

  def submit
    guesses = params[:guesses]

    SubmitGuesses.new(player: find_player, board: find_board, guesses: guesses).call

    redirect_to game_board_path(find_game, find_board)
  end

  private

  def find_game
    @find_game ||= Game.find(params[:game_id])
  end

  def find_board
    @find_board ||= find_game.boards.find(params[:id] || params[:board_id])
  end

  def find_player
    @find_player ||= find_game.players.where(user: current_user).first!
  end

  def find_guesses
    @find_guesses ||= find_board.guesses.where(player: find_player)
  end

end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_filter :authenticate
  # TODO check before_filter :set_game, only: [ :show, :delete, ... ] / except: [ :index ]

  def create
    game = join_game(current_user)

    redirect_to game_path(game)
  end

  def show
    @game = find_game
    @player = find_player

    respond_to do |format|
      format.html do
        if @game.started?
          board = @game.boards.last
        end

        if board && !board.finished?
          redirect_to game_board_path(@game, board)
        end
      end
      format.json { render :json => GamePresenter.new(@game).to_json }
    end
  end

  # TODO move to /games/2/players/1
  # ewwwwwwwww
  # use PATCH [:ready => true] instead of POST /ready (RESTful)
  def ready
    game = find_game

    find_player.update!(ready: true)

    if game.ready_to_start?
      CreateRound.new(game: game).call
    end

    redirect_to game_path(game)
  end

  # TODO move to /games/2/players/1
  def not_ready
    game = find_game

    find_player.update!(ready: false)

    redirect_to game_path(game)
  end

  private

  def find_game
    Game.find(params[:id] || params[:game_id])
  end

  def find_player
    find_game.players.where(user: current_user).first!
  end

  def join_game(user)
    JoinGame.new(user: user).call
  end

  def find_or_create_player(game)
    FindOrCreatePlayer.new(game: game).call
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def kick
    game = find_game
    player = find_player

    KickPlayer.new(game: game, player: player).call

    redirect_to game_path(game)
  end

  def find_game
    Game.find(params[:game_id])
  end

  def find_player
    find_game.players.where(id: params[:player_id]).first!
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth["provider"], :uid => auth["uid"]).first_or_initialize(
      :refresh_token => auth["credentials"]["refresh_token"],
      :access_token => auth["credentials"]["token"],
      :expires => auth["credentials"]["expires_at"],
      :name => auth["info"]["name"],
    )
    url = session[:return_to] || root_path
    session[:return_to] = nil
    url = root_path if url.eql?('/logout')

    if user.save
      session[:user_id] = user.id
      notice = "Signed in!"
      logger.debug "URL to redirect to: #{url}"
      redirect_to url, :notice => notice
    else
      raise "Failed to login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # TODO replace with @waiting_games for ps
  helper_method :waiting_games, :your_games, :active_games, :finished_games

  def index
  end

  private

  def waiting_games
    Game.not_started
  end

  def your_games
    current_user.players.order(created_at: :desc)
  end

  def active_games
    # TODO could/should be scopes one day
    your_games.reject { |p| p.game.finished? }.map(&:game)
  end

  def finished_games
    your_games.select { |p| p.game.finished? }.map(&:game)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
  def guess_classes(guess)
    classes = ["guess"]
    classes << "checked" if guess.checked?
    classes << "possible" if guess.possible?
    classes << "unique" if guess.unique?
    classes << "in-dictionary" if guess.in_dictionary?
    classes.join(" ")
  end

  def word_link(word)
    link_to word, "https://en.wiktionary.org/wiki/#{word}", title: "View '#{word}' on Wiktionary"
  end
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/board/_others_words.html.haml
.others-words.word-list
  %h3 All Players

  %table.all-players
    %tr
    - (@board.game.players - [@player]).each do |player|
      %td.player
        %h4= player.user.name

        - guesses = @board.guesses.where(player: player)

        %table
          %thead
            %tr
              %th Word
              %th Score
          %tbody
            - guesses.sort_by(&:word).each do |guess|
              %tr
                %td{ class: guess_classes(guess) }
                  - if guess.valid? && guess.possible? && guess.in_dictionary?
                    %i.guess-status.fa.fa-check
                  - elsif !guess.in_dictionary?
                    %i.guess-status.fa.fa-times
                  - else
                    %i.guess-status.nothing -

                  .word
                    - if guess.in_dictionary?
                      = word_link(guess.word)
                    - else
                      = guess.word

                  - if !guess.unique?
                    (#{pluralize(@board.guesses.where(word: guess.word).count, "person")} guessed)
                %td.score
                  = guess.score

          %tfoot
            %tr
              %td Total score
              %td= guesses.map(&:score).compact.inject(0, &:+)

.possible-words
  %h3 Unguessed Words

  != @board.possible_words.pluck(:word).reject { |w| @board.guesses.where(word: w).any? }.sort.map { |w| word_link(w) }.join(", ")

app/views/board/_timer.html.haml
.timer{ "data-date" => @board.expires_at.iso8601 }

app/views/board/_your_words.html.haml
.your-words.word-list
  %h3 Your Words

  - if @board.finished?
    %table
      %thead
        %tr
          %th Word
          %th Score
      %tbody
        - @guesses.sort_by(&:word).each do |guess|
          %tr
            %td{ class: guess_classes(guess) }
              - if guess.valid? && guess.possible? && guess.in_dictionary?
                %i.guess-status.fa.fa-check
              - elsif !guess.in_dictionary?
                %i.guess-status.fa.fa-times
              - else
                %i.guess-status.nothing -

              .word
                - if guess.in_dictionary?
                  = link_to guess.word, "https://en.wiktionary.org/wiki/#{guess.word}", title: "View on Wiktionary"
                - else
                  = guess.word

              - if !guess.unique?
                (#{pluralize(@board.guesses.where(word: guess.word).count, "person")} guessed)
            %td.score
              = guess.score

      %tfoot
        %tr
          %td Total score
          %td= @guesses.map(&:score).compact.inject(0, &:+)

    .actions
      %a.btn.next-round{ href: game_path(@game) }
        Next round
        %i.fa.fa-chevron-right

  - else
    #game-board{ "data-expires" => @board.expires_at.iso8601, "data-finished" => @board.finished? }
      = form_tag game_board_submit_path(@game, @board) do |f|
        = text_area_tag "guesses", @guesses.map(&:word).join("\n"), size: "25x10"
        .actions
          = submit_tag "Submit"

    = render partial: "timer"

app/views/board/show.html.haml
.board
  %h2
    %small
      = link_to "Game #{@game.id}", game_path(@game)
      >
    Round #{@board.round_number}
    - if @board.finished?
      (finished)

  .game-board
    %table.game-board-cells
      - @board.cells.each do |row|
        %tr
          - row.each do |cell|
            %td.cell= cell

  = render partial: "your_words"

  %dl.game-stats
    %dt Started
    %dd= @board.created_at

    - if @board.finished?
      %dt Finished
      %dd= @board.finished_at

    - else
      %dt Seconds left
      %dd.seconds-left (loading)

  - if @board.finished?
    = render partial: "others_words"

app/views/game/_recent_rounds.html.haml
.recent-rounds
  %h2 Recent rounds

  %table.recent-rounds
    %thead
      %tr
        %th Round
        - @game.players.each do |player|
          %th
            - if @player == player
              %i You!
            - else
              = player.user.name

    %tbody
      - @game.boards.order(round_number: :desc).limit(5).each do |board|
        %tr
          %td
            = link_to "Round #{board.round_number}", game_board_path(@game, board)
          - @game.players.each do |player|
            %td
              = board.guesses.where(player: player).map(&:score).inject(0, &:+)
      - if @game.boards.empty?
        %tr
          %td{ colspan: @game.players.count + 1 }
            %i (none yet!)

app/views/game/_score_board.html.haml
.score-board
  %h2 Score board

  %table.score-board
    %thead
      %tr
        %th Player
        %th.score Score
    %tbody
      - @game.players.order(score: :desc).each do |player|
        %tr
          %td.name
            - if @player == player
              %i You!
            - else
              = player.user.name
          %td.score
            = player.score

  .target-score
    First to #{@game.target_score} wins!

app/views/game/show.html.haml
- if @game.finished?
  .game.game-finished
    %h2 Game over

    %h3
      - winning_player = @game.players.order(score: :desc).first
      = winning_player.user.name
      - if @player == winning_player
        %i (you!)
      is the winner!
- else
  .game.game-waiting
    %h2 Waiting for players...

    %ul.player-list
      - @game.players.each do |player|
        %li.player{ class: player.ready? ? "ready" : "not-ready" }
          - if player.ready?
            %i.fa.fa-check-circle
          - else
            %i.fa.fa-times-circle
          = player.user.name

          - if player != @player
            = form_tag game_player_kick_path(@game, player), class: "kick-form" do |f|
              = submit_tag "Kick"

          - if player == @player
            %i.you (you!)

    .actions
      - if @player.ready?
        = form_tag game_not_ready_path(@game), class: "ready-form" do |f|
          = submit_tag "I'm not ready"

      - else
        = form_tag game_ready_path(@game), class: "ready-form" do |f|
          = submit_tag "I'm ready"

    #wait-for-game-to-start{ GamePresenter.new(@game).to_data_set }

    = render partial: "score_board"

    = render partial: "recent_rounds"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rboggle
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{ href: "http://fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic", rel: "stylesheet", type: "text/css" }
    %link{ href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", rel: "stylesheet", type: "text/css" }

  %body
    %nav
      %ul.navigation
        %li.home= link_to "Rboggle", root_path
        - if current_user
          %li.user
            Logged in as
            %i= current_user.name
          %li.logout= link_to "Log out", logout_path
        - else
          %li.login= link_to "Log in", login_path

    - if flash.alert
      .flash.alert=flash.alert

    - if flash.notice
      .flash.notice=flash.notice

    .content
      = yield

    %footer
      Contribute on
      = link_to "GitHub", "https://github.com/soundasleep/rboggle", class: "github"

app/views/welcome/index.html.haml
.welcome
  %h1 Boggle

  %p.description
    A multiplayer
    = link_to "open source", "https://github.com/soundasleep/rboggle"
    implementation of Boggle in Ruby on Rails.

  - if current_user
    = form_tag game_index_path, method: :create do |f|
      = submit_tag "Play a game"

      %i.tip
        = pluralize(waiting_games.count, "game")
        waiting to start

    %h2 Active games

    %ul
      - active_games.each do |game|
        %li
          = link_to pluralize(game.players.count, "player"), game_path(game)
          = pluralize(game.rounds, "round")
      - if active_games.empty?
        %li.empty
          %i (none)

    %h2 Finished games

    %ul
      - finished_games.each do |game|
        %li
          = link_to pluralize(game.players.count, "player"), game_path(game)
          = pluralize(game.rounds, "round")
      - if finished_games.empty?
        %li.empty
          %i (none)

  - else
    %p You need to #{link_to "log in", login_path} first.

  %h2 Dictionary

  #{pluralize(Dictionary.count, "word")} in the dictionary.